In [5]:
import torch

x = torch.Tensor ([5,3,10])
y = torch.Tensor ([2,1,0])

print(x*y)

tensor([10.,  3.,  0.])


In [7]:
x = torch.zeros([2,2])
print (x)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
x.shape

torch.Size([2, 2])

In [15]:
y = torch.rand([3,3])
print(y)

tensor([[0.8295, 0.8524, 0.9245],
        [0.5207, 0.1123, 0.5106],
        [0.4540, 0.6195, 0.0505]])


In [17]:
y = y.view([1,9])


In [14]:
print(y)

tensor([[0.3294, 0.0997, 0.2982, 0.8028, 0.3881, 0.1975, 0.4855, 0.7854, 0.6456]])


In [18]:
pip install torchvision

You should consider upgrading via the '/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p36/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torcv